#!/bin/bash
# DNS-CLAW — First-run setup script
# Checks deps, configures provider, generates keys, and builds.
set -e

# ── Colors ──────────────────────────────────────────────────────────────────
R1='\033[38;2;255;60;50m'
R2='\033[38;2;255;100;80m'
R3='\033[38;2;255;140;110m'
R4='\033[38;2;255;195;180m'
DIM='\033[38;2;100;80;80m'
RST='\033[0m'
BOLD='\033[1m'

info()  { echo -e "  ${R2}│${RST}  $1"; }
ok()    { echo -e "  ${R2}│  ${R3}✓${RST} $1"; }
err()   { echo -e "  ${R1}│  ✗${RST} $1"; }
prompt(){ echo -ne "  ${R2}│${RST}  $1"; }

# ── Banner ──────────────────────────────────────────────────────────────────
echo ""
echo -e "\033[38;2;255;20;20m▓█████▄  ███▄    █   ██████     ▄████▄   ██▓    ▄▄▄       █     █░${RST}"
echo -e "\033[38;2;255;60;50m▒██▀ ██▌ ██ ▀█   █ ▒██    ▒    ▒██▀ ▀█  ▓██▒   ▒████▄    ▓█░ █ ░█░${RST}"
echo -e "\033[38;2;255;100;80m░██   █▌▓██  ▀█ ██▒░ ▓██▄      ▒▓█    ▄ ▒██░   ▒██  ▀█▄  ▒█░ █ ░█ ${RST}"
echo -e "\033[38;2;255;140;110m░▓█▄   ▌▓██▒  ▐▌██▒  ▒   ██▒   ▒▓▓▄ ▄██▒▒██░   ░██▄▄▄▄██ ░█░ █ ░█ ${RST}"
echo -e "\033[38;2;255;170;150m░▒████▓ ▒██░   ▓██░▒██████▒▒   ▒ ▓███▀ ░░██████▒▓█   ▓██▒░░██▒██▓ ${RST}"
echo -e "\033[38;2;255;195;180m ▒▒▓  ▒ ░ ▒░   ▒ ▒ ▒ ▒▓▒ ▒ ░   ░ ░▒ ▒  ░░ ▒░▓  ░▒▒   ▓▒█░░ ▓░▒ ▒  ${RST}"
echo -e "\033[38;2;255;215;210m ░ ▒  ▒ ░ ░░   ░ ▒░░ ░▒  ░ ░     ░  ▒   ░ ░ ▒  ░ ▒   ▒▒ ░  ▒ ░ ░  ${RST}"
echo -e "\033[38;2;255;230;225m ░ ░  ░    ░   ░ ░ ░  ░  ░     ░          ░ ░    ░   ▒     ░   ░  ${RST}"
echo -e "\033[38;2;255;245;242m   ░             ░       ░     ░ ░          ░  ░     ░  ░    ░    ${RST}"
echo -e "\033[38;2;255;255;255m ░                             ░                                  ${RST}"
echo ""
echo -e "  ${R2}┌─ Setup ${DIM}──────────────────────────────────${RST}"
echo -e "  ${R2}│${RST}"

# ── Check dependencies ─────────────────────────────────────────────────────
info "Checking dependencies..."

MISSING=""
for cmd in cmake openssl; do
    if ! command -v "$cmd" &>/dev/null; then
        MISSING="$MISSING $cmd"
    fi
done

if ! command -v curl &>/dev/null; then
    MISSING="$MISSING curl"
fi

if [ -n "$MISSING" ]; then
    err "Missing:${MISSING}"
    info "Install with: ${BOLD}brew install${MISSING}${RST}"
    echo -e "  ${R2}└${DIM}──────────────────────────────────────────${RST}"
    exit 1
fi
ok "All dependencies found"
echo -e "  ${R2}│${RST}"

# ── Config directory ────────────────────────────────────────────────────────
CONFIG_DIR="$HOME/.config/dnsclaw"
ENV_FILE="$CONFIG_DIR/.env"
mkdir -p "$CONFIG_DIR"

# ── Provider setup ──────────────────────────────────────────────────────────
HAS_KEY=0
if [ -f "$ENV_FILE" ]; then
    for key in GEMINI_API_KEY OPENAI_API_KEY ANTHROPIC_API_KEY OPENROUTER_API_KEY; do
        if grep -q "^${key}=" "$ENV_FILE" 2>/dev/null; then
            VAL=$(grep "^${key}=" "$ENV_FILE" | head -1 | cut -d= -f2 | tr -d '"' | tr -d "'")
            if [ -n "$VAL" ] && [ "$VAL" != "your-api-key-here" ]; then
                HAS_KEY=1
                ok "Found existing config at $ENV_FILE"
                break
            fi
        fi
    done
fi

if [ "$HAS_KEY" -eq 0 ]; then
    info "Select your LLM provider:"
    echo -e "  ${R2}│${RST}"
    echo -e "  ${R2}│${RST}    ${R3}1)${RST} Gemini"
    echo -e "  ${R2}│${RST}    ${R3}2)${RST} OpenAI"
    echo -e "  ${R2}│${RST}    ${R3}3)${RST} Claude (Anthropic)"
    echo -e "  ${R2}│${RST}    ${R3}4)${RST} OpenRouter"
    echo -e "  ${R2}│${RST}"
    prompt "Choice [1-4]: "
    read -r CHOICE

    case "$CHOICE" in
        1) KEY_NAME="GEMINI_API_KEY";     MODEL_NAME="GEMINI_MODEL";     DEFAULT_MODEL="gemini-3.1-pro-preview" ;;
        2) KEY_NAME="OPENAI_API_KEY";     MODEL_NAME="OPENAI_MODEL";     DEFAULT_MODEL="gpt-5.4" ;;
        3) KEY_NAME="ANTHROPIC_API_KEY";  MODEL_NAME="ANTHROPIC_MODEL";  DEFAULT_MODEL="claude-opus-4-6-20250610" ;;
        4) KEY_NAME="OPENROUTER_API_KEY"; MODEL_NAME="OPENROUTER_MODEL"; DEFAULT_MODEL="openrouter/auto" ;;
        *) err "Invalid choice"; exit 1 ;;
    esac

    prompt "Paste your API key: "
    read -rs API_KEY
    echo ""
    if [ -z "$API_KEY" ]; then
        err "No API key provided"
        exit 1
    fi
    ok "API key received"

    prompt "Model (enter for ${DEFAULT_MODEL}): "
    read -r MODEL
    [ -z "$MODEL" ] && MODEL="$DEFAULT_MODEL"

    echo -e "  ${R2}│${RST}"

    # Generate PSK
    PSK=$(openssl rand -base64 32)

    # Write config
    cat > "$ENV_FILE" <<ENVEOF
# DNS-CLAW Configuration
# Generated by setup.sh

# LLM Provider
${KEY_NAME}="${API_KEY}"
${MODEL_NAME}="${MODEL}"

# Payload Encryption (AES-256-GCM)
TUNNEL_PSK="${PSK}"

# Transport (UDP is default; set ONE to true for TLS)
USE_DOT=false
USE_DOH=false

# Server address
DNS_SERVER_ADDR=127.0.0.1
SERVER_PORT=53
INSECURE_SKIP_VERIFY=true

# TLS certs (only needed for DoT/DoH)
TLS_CERT=cert.pem
TLS_KEY=key.pem
ENVEOF

    chmod 600 "$ENV_FILE"
    ok "Config saved to $ENV_FILE"
    ok "Generated encryption key (TUNNEL_PSK)"
fi

echo -e "  ${R2}│${RST}"

# ── Transport choice ───────────────────────────────────────────────────────
prompt "Transport mode? [${BOLD}1${RST}] UDP  [2] DoT  [3] DoH: "
read -r TRANSPORT

case "$TRANSPORT" in
    2)
        sed -i.bak 's/USE_DOT=false/USE_DOT=true/' "$ENV_FILE"
        sed -i.bak 's/SERVER_PORT=53/SERVER_PORT=853/' "$ENV_FILE"
        rm -f "$ENV_FILE.bak"
        ok "Transport: DNS-over-TLS (port 853)"
        NEED_CERTS=1
        ;;
    3)
        sed -i.bak 's/USE_DOH=false/USE_DOH=true/' "$ENV_FILE"
        sed -i.bak 's/SERVER_PORT=53/SERVER_PORT=443/' "$ENV_FILE"
        sed -i.bak 's|DNS_SERVER_ADDR=127.0.0.1|DNS_SERVER_ADDR=https://127.0.0.1/dns-query|' "$ENV_FILE"
        rm -f "$ENV_FILE.bak"
        ok "Transport: DNS-over-HTTPS (port 443)"
        NEED_CERTS=1
        ;;
    *)
        ok "Transport: UDP (port 53)"
        ;;
esac

# ── Generate TLS certs if needed ───────────────────────────────────────────
if [ "${NEED_CERTS:-0}" = "1" ]; then
    echo -e "  ${R2}│${RST}"
    info "Generating TLS certificates..."
    openssl req -x509 -nodes -days 365 \
        -newkey rsa:2048 \
        -keyout key.pem \
        -out cert.pem \
        -subj "/CN=llm.local" \
        -addext "subjectAltName=DNS:llm.local,DNS:localhost,IP:127.0.0.1" \
        2>/dev/null
    ok "Generated cert.pem and key.pem"
fi

echo -e "  ${R2}│${RST}"

# ── Build ──────────────────────────────────────────────────────────────────
info "Building DNS-CLAW..."

CMAKE_ARGS="-DCMAKE_BUILD_TYPE=Release"

# Detect build tool
if command -v ninja &>/dev/null; then
    cmake -B build -G Ninja $CMAKE_ARGS 2>&1 | tail -1
    cmake --build build 2>&1 | tail -1
else
    cmake -B build $CMAKE_ARGS 2>&1 | tail -1
    cmake --build build 2>&1 | tail -1
fi

ok "Build complete"
echo -e "  ${R2}│${RST}"

# ── Done ───────────────────────────────────────────────────────────────────
echo -e "  ${R2}│${RST}  ${BOLD}Ready to go!${RST}"
echo -e "  ${R2}│${RST}"
echo -e "  ${R2}│${RST}  Start the server (requires sudo for port binding):"
echo -e "  ${R2}│${RST}    ${R3}\$ sudo -E ./build/dnsclaw-server${RST}"
echo -e "  ${R2}│${RST}"
echo -e "  ${R2}│${RST}  Then in another terminal:"
echo -e "  ${R2}│${RST}    ${R3}\$ ./build/dnsclaw${RST}"
echo -e "  ${R2}│${RST}"
echo -e "  ${R2}│${RST}  Or install system-wide:"
echo -e "  ${R2}│${RST}    ${R3}\$ sudo cmake --install build${RST}"
echo -e "  ${R2}│${RST}    ${R3}\$ sudo -E dnsclaw-server${RST}  &  ${R3}dnsclaw${RST}"
echo -e "  ${R2}│${RST}"
echo -e "  ${R2}└${DIM}──────────────────────────────────────────${RST}"
echo ""
